- package.json
> [figma]:update to 0.1.15

- package.json
> [figma]:update to 0.1.30

- package.json
> [figma]:update to 0.1.31

- package.json
1. 新增 29_me_solid、29_mail、29_search；
> [figma]:update to 0.1.32

- package.json
> [figma]:update to 0.1.33

- package.json
> [figma]:update to 0.1.34

- package.json
> [figma]:update to 0.1.35

- package.json
> [figma]:update to 0.1.36

- package.json
> [figma]:update to 0.1.37

- package.json
> [figma]:update to 0.1.38

- package.json
> [figma]:update to 0.1.39

- package.json
> [figma]:update to 0.1.40

- package.json
> [figma]:update to 0.1.41

- package.json
> [figma]:update to 0.1.42

- package.json
> [figma]:update to 0.1.43

- package.json
> [figma]:update to 0.1.44

- package.json
> [figma]:update to 0.1.45

- package.json
1. Fixed 圆角问题，我的页：客服、家族树、优惠券、订单、设置图标；
> [figma]:update to 0.1.46

- package.json
> [figma]:update to 0.1.47

- package.json
> [figma]:update to 0.1.48

- package.json
> [figma]:update to 0.1.49

- package.json
> [figma]:update to 0.1.50

- package.json
> [figma]:update to 0.1.51

- package.json
1. 沙漏图标上传不显示，图标库 Bug 吗？
2. 新增一个五角星图标，测试一下看看；
> [figma]:update to 0.1.52

- package.json
> [figma]:update to 0.1.54

- package.json
> [figma]:update to 0.1.55

- package.json
> [figma]:update to 0.1.56

- package.json
> [figma]:update to 0.1.57

- package.json
> [figma]:update to 0.1.59

- package.json
> [figma]:update to 0.1.60

- package.json
1. 新增 24 号，3 个图标，分别是 Y、Book、Photo；
> [figma]:update to 0.1.62

- package.json
> [figma]:update to 0.1.64

- package.json
> [figma]:update to 0.1.73

- package.json
> [figma]:update to 0.1.74

- package.json
> [figma]:update to 0.1.75

- package.json
> [figma]:update to 0.1.76

- package.json
> [figma]:update to 0.1.78

- package.json
1. 新增 Y 六角形图标、社区讨论图标、切换排序图标——共3枚新图标；
> [figma]:update to 0.1.80

- package.json
1. 新增 Y 六角形图标、社区讨论图标、切换排序图标——共3枚新图标；（修正Y图标）
> [figma]:update to 0.1.81

- package.json
> [figma]:update to 0.1.82

- package.json
> [figma]:update to 1.17.8

- package.json
> [figma]:update to 1.17.9

- package.json
> [figma]:update to 1.17.10

- package.json
> [figma]:update to 1.17.11

- package.json
> [figma]:update to 1.17.12

- package.json
> [figma]:update to 1.17.14

- package.json
1. 修复扫码彩色和管理检测人彩色图标；
2. 新增26_book图标；
> [figma]:update to 1.17.15

- package.json
> [figma]:update to 1.17.16

- package.json
> [figma]:update to 1.17.17

- package.json
> [figma]:update to 1.17.18

- package.json
> [figma]:update to 1.17.19

- package.json
> [figma]:update to 1.17.20

- package.json
> [figma]:update to 1.17.21

- package.json
> [figma]:update to 1.17.22

- package.json
> [figma]:update to 1.17.23

- .github/workflows/figma.yml
移除冗余字段（重点在移除 dependencies 以避免重复安装依赖）
> feat: 发布时移除 package.json 中的冗余字段

- package.json
> [figma]:update to 1.17.24

- package.json
> [figma]:update to 1.17.25

- package.json
> [figma]:update to 1.17.26

- package.json
> [figma]:update to 1.17.27

- package.json
> [figma]:update to 1.17.28

- package.json
> [figma]:update to 1.17.29

- package.json
> [figma]:update to 1.17.30

- package.json
> [figma]:update to 1.17.31

- package.json
> [figma]:update to 1.17.32

- package.json
> [figma]:update to 1.17.33

- package.json
> [figma]:update to 1.17.34

- package.json
> [figma]:update to 1.17.35

- package.json
> [figma]:update to 1.17.37

- package.json
> [figma]:update to 1.17.38

- package.json
> [figma]:update to 1.17.39

- package.json
> [figma]:update to 1.17.40

- package.json
> [figma]:update to 1.17.41

- package.json
> [figma]:update to 1.17.42

- package.json
> [figma]:update to 1.17.43

- package.json
> [figma]:update to 1.17.44

- package.json
> [figma]:update to 1.17.45
